version: '3.3'
services:
  postgres:
    image: postgres:13.4
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 341146406
      POSTGRES_USER: postgres
      POSTGRES_DB: telegramBot_db
    restart: always
  app:
    image: telegram-bot-demo
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: always