version: '3.3'
services:
  postgres:
    image: postgres:13.4
    ports:
    - 5432:5432
    restart: always
  app:
    image: telegramBotDemo
    depends_on:
      - postgres
    ports:
      - 8086:8086
    restart: always